const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/P1.jpg',
      price: 120,
      countInstock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Fit Shirt',
      slug: 'nike-fit-shirt',
      category: 'Shirts',
      image: '/images/P2.png',
      price: 250,
      countInstock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/P3.jpg',
      price: 90,
      countInstock: 5,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/P4.jpg',
      price: 100,
      countInstock: 15,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 14,
      description: 'high quality shirt',
    },
  ],
};
export default data;
